import 'reset-css/reset.css';

import { createGlobalStyle } from "styled-components";

export const $DAWN_LIGHT_GOLD = '#DEBB9C';
export const $DAWN_BLACK = '#0F0700';

export const $GOLD_BORDER = `border: solid ${$DAWN_LIGHT_GOLD} 1px;`;

export const GlobalStyle = createGlobalStyle`
    html, body {
        font-family: "Meiryo UI";
        font-size: 12pt;
        height: 100%;
        width: 100%;
        background-color: ${$DAWN_BLACK};
    }
    button {
        background-color: #ccc;
        border-radius: 5px;
        border-style: none;
        cursor: pointer;
        padding: .5em;
        transition-property: all;
        transition-duration: .2s;
        &:hover {
            box-shadow: 3px 3px 3px rgba(200,200,200,4);
            transform: translate(-2px, -2px);
        }
        &:active {
            background-color: #cccc00;
        }
    }
    input[type=text] {
        border-radius: 5px;
        border: 1px solid #ddd;
        padding: .5em;
    }
`;

export const $COLOR_PRIMARY_0 = '#723FBD';  // MAIN PRIMARY COLOR */
export const $COLOR_PRIMARY_1 = '#AE8CE2';
export const $COLOR_PRIMARY_2 = '#8C5FCF';
export const $COLOR_PRIMARY_3 = '#5A21AF';
export const $COLOR_PRIMARY_4 = '#410E8D';

export const $COLOR_SECONDARY_1_0 = '#30B698';  // MAIN SECONDARY COLOR (1) */
export const $COLOR_SECONDARY_1_1 = '#81DFCA';
export const $COLOR_SECONDARY_1_2 = '#52CAAF';
export const $COLOR_SECONDARY_1_3 = '#12A785';
export const $COLOR_SECONDARY_1_4 = '#028568';

export const $COLOR_SECONDARY_2_0 = '#FF5644';  // MAIN SECONDARY COLOR (2) */

// Generated by Paletton.com © 2002-2014 */
// http://paletton.com */

export const $COLOR_FOREGROUND = '#333';
export const $COLOR_FOREGROUND_REVERSE = '#fff';
